#!/usr/bin/env bash

cd ~/projects/solorumgroup/webappsolorumgroup && \
yarn build && \
cd ~/projects/solorumgroup/webappsolorumgroup-admin && \
yarn build && \
cd ~/projects/solorumgroup/solorum.ru && \
git add -u
git commit -m "version $1"
git push github master
